name: "Validate Gradle Wrapper"

on:
  push:
    branches:
      - main
      - android-10
  pull_request:
    branches:
      - main
      - android-10

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v3
