name: Unit tests

on:
  push:
    branches:
      - main
      - android-10
  pull_request:
    branches:
      - main
      - android-10

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Execute tests
      run: |
        ./gradlew test
